<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AttributeSeeder extends Seeder
{
    public function run()
    {
        $attributes = [
            ['type' => 'basic_information', 'value' => 'age_prompt', 'label' => 'Please share your age:', 'description' => 'Prompt asking for user\'s age'],
            ['type' => 'basic_information', 'value' => 'age_error', 'label' => 'Please enter a valid age between 12 and 120', 'description' => 'Error message for invalid age input'],
            ['type' => 'basic_information', 'value' => 'gender_prompt', 'label' => 'Please select your gender:', 'description' => 'Prompt asking for user\'s gender'],
            ['type' => 'basic_information', 'value' => 'male', 'label' => 'Male', 'description' => 'Male gender'],
            ['type' => 'basic_information', 'value' => 'female', 'label' => 'Female', 'description' => 'Female gender'],
            ['type' => 'basic_information', 'value' => 'other', 'label' => 'Other', 'description' => 'Other gender'],
            ['type' => 'basic_information', 'value' => 'height_prompt', 'label' => 'Please share your height (in cm or feet-inches):', 'description' => 'Prompt asking for user\'s height'],
            ['type' => 'basic_information', 'value' => 'weight_prompt', 'label' => 'Please share your current weight (in kg or lbs):', 'description' => 'Prompt asking for user\'s weight'],
            ['type' => 'basic_information', 'value' => 'target_weight_prompt', 'label' => 'Please share your target weight, or type "same":', 'description' => 'Prompt asking for target weight'],

            // **Region**
            ['type' => 'region', 'value' => 'country_prompt', 'label' => 'Which country do you live in?', 'description' => 'Prompt asking for country'],
            ['type' => 'region', 'value' => 'state_prompt', 'label' => 'Which state or region do you live in?', 'description' => 'Prompt asking for state or region'],
            ['type' => 'region', 'value' => 'city_prompt', 'label' => 'Which city do you live in?', 'description' => 'Prompt asking for city'],

            // **Activity**
            ['type' => 'activity', 'value' => 'activity_prompt', 'label' => 'Which describes your activity level?', 'description' => 'Prompt asking for activity level'],
            ['type' => 'activity', 'value' => 'activity_header', 'label' => 'Activity Level', 'description' => 'Header for activity level section'],
            ['type' => 'activity', 'value' => 'activity_body', 'label' => 'Select your typical activity', 'description' => 'Body text explaining activity level'],
            ['type' => 'activity', 'value' => 'sedentary', 'label' => 'Sedentary', 'description' => 'Sedentary activity level'],
            ['type' => 'activity', 'value' => 'light_active', 'label' => 'Lightly active', 'description' => 'Lightly active activity level'],
            ['type' => 'activity', 'value' => 'mod_active', 'label' => 'Moderately active', 'description' => 'Moderately active activity level'],
            ['type' => 'activity', 'value' => 'very_active', 'label' => 'Very active', 'description' => 'Very active activity level'],
            ['type' => 'activity', 'value' => 'extreme_active', 'label' => 'Extremely active', 'description' => 'Extremely active activity level'],

            // **Health**
            ['type' => 'health', 'value' => 'health_prompt', 'label' => 'Any health conditions?', 'description' => 'Prompt asking for health conditions'],
            ['type' => 'health', 'value' => 'health_header', 'label' => 'Health Conditions', 'description' => 'Header for health conditions section'],
            ['type' => 'health', 'value' => 'health_body', 'label' => 'Select all that apply', 'description' => 'Body text explaining health conditions options'],
            ['type' => 'health', 'value' => 'diabetes', 'label' => 'Diabetes', 'description' => 'Health condition - Diabetes'],
            ['type' => 'health', 'value' => 'hypertension', 'label' => 'Hypertension', 'description' => 'Health condition - Hypertension'],
            ['type' => 'health', 'value' => 'heart', 'label' => 'Heart disease', 'description' => 'Health condition - Heart disease'],
            ['type' => 'health', 'value' => 'kidney', 'label' => 'Kidney issues', 'description' => 'Health condition - Kidney issues'],
            ['type' => 'health', 'value' => 'liver', 'label' => 'Liver problems', 'description' => 'Health condition - Liver problems'],
            ['type' => 'health', 'value' => 'digestive', 'label' => 'Digestive disorders', 'description' => 'Health condition - Digestive disorders'],
            ['type' => 'health', 'value' => 'thyroid', 'label' => 'Thyroid issues', 'description' => 'Health condition - Thyroid issues'],
            ['type' => 'health', 'value' => 'none_health', 'label' => 'None of these', 'description' => 'No health conditions'],
            ['type' => 'health', 'value' => 'health_details_prompt', 'label' => 'More details about your health:', 'description' => 'Prompt for additional health details'],

            // **Diet**
            ['type' => 'diet', 'value' => 'diet_prompt', 'label' => 'What diet do you follow?', 'description' => 'Prompt asking for diet'],
            ['type' => 'diet', 'value' => 'diet_header', 'label' => 'Diet Type', 'description' => 'Header for diet section'],
            ['type' => 'diet', 'value' => 'diet_body', 'label' => 'Select your eating style', 'description' => 'Body text explaining diet options'],
            ['type' => 'diet', 'value' => 'omnivore', 'label' => 'Omnivore', 'description' => 'Diet type - Omnivore'],
            ['type' => 'diet', 'value' => 'vegetarian', 'label' => 'Vegetarian', 'description' => 'Diet type - Vegetarian'],
            ['type' => 'diet', 'value' => 'eggetarian', 'label' => 'Vegetarian + eggs', 'description' => 'Diet type - Vegetarian with eggs'],
            ['type' => 'diet', 'value' => 'vegan', 'label' => 'Vegan', 'description' => 'Diet type - Vegan'],
            ['type' => 'diet', 'value' => 'jain', 'label' => 'Jain', 'description' => 'Diet type - Jain'],
            ['type' => 'diet', 'value' => 'keto', 'label' => 'Keto', 'description' => 'Diet type - Keto'],
            ['type' => 'diet', 'value' => 'other_diet', 'label' => 'Other', 'description' => 'Other diet type'],
            ['type' => 'diet', 'value' => 'pescatarian', 'label' => 'Pescatarian', 'description' => 'Diet type - Pescatarian'],
            ['type' => 'diet', 'value' => 'flexitarian', 'label' => 'Flexitarian', 'description' => 'Diet type - Flexitarian'],
            ['type' => 'diet', 'value' => 'mediterranean', 'label' => 'Mediterranean', 'description' => 'Diet type - Mediterranean'],
            ['type' => 'diet', 'value' => 'dash', 'label' => 'DASH', 'description' => 'Diet type - DASH'],
            ['type' => 'diet', 'value' => 'fodmap', 'label' => 'FODMAP', 'description' => 'Diet type - FODMAP'],
            ['type' => 'diet', 'value' => 'raw_food', 'label' => 'Raw food', 'description' => 'Diet type - Raw food'],
            ['type' => 'diet', 'value' => 'diet_type_other_prompt', 'label' => 'Please describe your diet type:', 'description' => 'Prompt asking for other diet type'],

            // **Spice Preference**
            ['type' => 'spice_preference', 'value' => 'spice_preference_prompt', 'label' => 'What is your spice preference?', 'description' => 'Prompt asking for spice preference'],
            ['type' => 'spice_preference', 'value' => 'spice_preference_header', 'label' => 'Spice Level', 'description' => 'Header for spice preference section'],
            ['type' => 'spice_preference', 'value' => 'spice_preference_body', 'label' => 'Select your preferred spice level', 'description' => 'Body text explaining spice preference options'],
            ['type' => 'spice_preference', 'value' => 'mild_spice', 'label' => 'Mild (no spice)', 'description' => 'Mild spice preference'],
            ['type' => 'spice_preference', 'value' => 'low_spice', 'label' => 'Low spice', 'description' => 'Low spice preference'],
            ['type' => 'spice_preference', 'value' => 'medium_spice', 'label' => 'Medium spice', 'description' => 'Medium spice preference'],
            ['type' => 'spice_preference', 'value' => 'spicy', 'label' => 'Spicy', 'description' => 'Spicy preference'],
            ['type' => 'spice_preference', 'value' => 'very_spicy', 'label' => 'Very spicy', 'description' => 'Very spicy preference'],

            // **Allergies**
            ['type' => 'allergies', 'value' => 'allergies_prompt', 'label' => 'Any food allergies?', 'description' => 'Prompt asking for allergies'],
            ['type' => 'allergies', 'value' => 'allergies_header', 'label' => 'Food Allergies', 'description' => 'Header for food allergies section'],
            ['type' => 'allergies', 'value' => 'allergies_body', 'label' => 'Select all that apply', 'description' => 'Body text explaining allergies options'],
            ['type' => 'allergies', 'value' => 'dairy', 'label' => 'Dairy', 'description' => 'Dairy allergy'],
            ['type' => 'allergies', 'value' => 'gluten', 'label' => 'Gluten', 'description' => 'Gluten allergy'],
            ['type' => 'allergies', 'value' => 'nuts', 'label' => 'Nuts', 'description' => 'Nuts allergy'],
            ['type' => 'allergies', 'value' => 'seafood', 'label' => 'Seafood', 'description' => 'Seafood allergy'],
            ['type' => 'allergies', 'value' => 'eggs', 'label' => 'Eggs', 'description' => 'Eggs allergy'],
            ['type' => 'allergies', 'value' => 'soy', 'label' => 'Soy', 'description' => 'Soy allergy'],
            ['type' => 'allergies', 'value' => 'other_allergy', 'label' => 'Other', 'description' => 'Other allergy'],
            ['type' => 'allergies', 'value' => 'none', 'label' => 'None', 'description' => 'No allergy'],
            ['type' => 'allergies', 'value' => 'tree_nuts', 'label' => 'Tree nuts', 'description' => 'Tree nuts allergy'],
            ['type' => 'allergies', 'value' => 'peanuts', 'label' => 'Peanuts', 'description' => 'Peanuts allergy'],
            ['type' => 'allergies', 'value' => 'corn', 'label' => 'Corn', 'description' => 'Corn allergy'],
            ['type' => 'allergies', 'value' => 'fruits', 'label' => 'Fruits', 'description' => 'Fruits allergy'],
            ['type' => 'allergies', 'value' => 'nightshades', 'label' => 'Nightshades', 'description' => 'Nightshades allergy'],
            ['type' => 'allergies', 'value' => 'sulfites', 'label' => 'Sulfites', 'description' => 'Sulfites allergy'],
            ['type' => 'allergies', 'value' => 'fodmaps', 'label' => 'FODMAPs', 'description' => 'FODMAPs allergy'],
            ['type' => 'allergies', 'value' => 'none_allergy', 'label' => 'None', 'description' => 'No allergy'],
            ['type' => 'allergies', 'value' => 'allergy_details_prompt', 'label' => 'Please provide details about your specific food allergies or intolerances:', 'description' => 'Prompt for allergy details'],

            // **Restrictions**
            ['type' => 'restrictions', 'value' => 'restrictions_prompt', 'label' => 'Foods you avoid?', 'description' => 'Prompt asking for food restrictions'],
            ['type' => 'restrictions', 'value' => 'restrictions_header', 'label' => 'Food Restrictions', 'description' => 'Header for food restrictions section'],
            ['type' => 'restrictions', 'value' => 'restrictions_body', 'label' => 'Select foods you avoid', 'description' => 'Body text explaining food restrictions'],
            ['type' => 'restrictions', 'value' => 'red_meat', 'label' => 'Red meat', 'description' => 'Avoid red meat'],
            ['type' => 'restrictions', 'value' => 'poultry', 'label' => 'Poultry', 'description' => 'Avoid poultry'],
            ['type' => 'restrictions', 'value' => 'seafood_r', 'label' => 'Seafood', 'description' => 'Avoid seafood'],
            ['type' => 'restrictions', 'value' => 'eggs_r', 'label' => 'Eggs', 'description' => 'Avoid eggs'],
            ['type' => 'restrictions', 'value' => 'dairy_r', 'label' => 'Dairy', 'description' => 'Avoid dairy'],
            ['type' => 'restrictions', 'value' => 'onion_garlic', 'label' => 'Onion/Garlic', 'description' => 'Avoid onion and garlic'],
            ['type' => 'restrictions', 'value' => 'processed', 'label' => 'Processed foods', 'description' => 'Avoid processed foods'],
            ['type' => 'restrictions', 'value' => 'none_r', 'label' => 'None', 'description' => 'No restrictions'],
            ['type' => 'restrictions', 'value' => 'wheat_gluten', 'label' => 'Wheat/Gluten', 'description' => 'Avoid wheat/gluten'],
            ['type' => 'restrictions', 'value' => 'soy_r', 'label' => 'Soy', 'description' => 'Avoid soy'],
            ['type' => 'restrictions', 'value' => 'nightshades_r', 'label' => 'Nightshades', 'description' => 'Avoid nightshades'],
            ['type' => 'restrictions', 'value' => 'root_veg', 'label' => 'Root vegetables', 'description' => 'Avoid root vegetables'],
            ['type' => 'restrictions', 'value' => 'nuts_r', 'label' => 'Nuts', 'description' => 'Avoid nuts'],
            ['type' => 'restrictions', 'value' => 'added_sugar', 'label' => 'Added sugar', 'description' => 'Avoid added sugar'],
            ['type' => 'restrictions', 'value' => 'other_restriction', 'label' => 'Other', 'description' => 'Other food restrictions'],
            ['type' => 'restrictions', 'value' => 'none_restriction', 'label' => 'None', 'description' => 'No food restrictions'],
            ['type' => 'restrictions', 'value' => 'food_restrictions_other_prompt', 'label' => 'Please specify other foods you avoid:', 'description' => 'Prompt for specifying other restrictions'],

            // **Goals**
            ['type' => 'goals', 'value' => 'goal_prompt', 'label' => 'Your primary health goal?', 'description' => 'Prompt asking for primary health goal'],
            ['type' => 'goals', 'value' => 'goal_header', 'label' => 'Primary Goal', 'description' => 'Header for goals section'],
            ['type' => 'goals', 'value' => 'goal_body', 'label' => 'Select main objective', 'description' => 'Body text explaining goal options'],
            ['type' => 'goals', 'value' => 'weight_loss', 'label' => 'Weight loss', 'description' => 'Goal to lose weight'],
            ['type' => 'goals', 'value' => 'muscle_gain', 'label' => 'Muscle gain', 'description' => 'Goal to gain muscle'],
            ['type' => 'goals', 'value' => 'maintain', 'label' => 'Maintain weight', 'description' => 'Goal to maintain current weight'],
            ['type' => 'goals', 'value' => 'energy', 'label' => 'Better energy', 'description' => 'Goal for more energy'],
            ['type' => 'goals', 'value' => 'health', 'label' => 'Improve health', 'description' => 'Goal to improve health'],
            ['type' => 'goals', 'value' => 'digestion', 'label' => 'Improved digestion', 'description' => 'Goal for better digestion'],
            ['type' => 'goals', 'value' => 'overall_health', 'label' => 'Improved overall health', 'description' => 'Goal for better overall health'],
            ['type' => 'goals', 'value' => 'recovery', 'label' => 'Recovery from condition', 'description' => 'Goal for recovery from an illness or condition'],
            ['type' => 'goals', 'value' => 'athletic', 'label' => 'Athletic performance', 'description' => 'Goal to improve athletic performance'],
            ['type' => 'goals', 'value' => 'longevity', 'label' => 'Longevity & prevention', 'description' => 'Goal for long-term health and prevention'],
            ['type' => 'goals', 'value' => 'hormone_balance', 'label' => 'Hormone balance', 'description' => 'Goal to balance hormones'],
            ['type' => 'goals', 'value' => 'mental_clarity', 'label' => 'Mental clarity', 'description' => 'Goal for better mental clarity'],
            ['type' => 'goals', 'value' => 'other_goal', 'label' => 'Other', 'description' => 'Other health goal'],

            // **Recovery Needs**
            ['type' => 'recovery_needs', 'value' => 'recovery_needs_prompt', 'label' => 'Are you looking to address any specific health concerns?', 'description' => 'Prompt asking for recovery needs'],
            ['type' => 'recovery_needs', 'value' => 'recovery_needs_header', 'label' => 'Health Goals', 'description' => 'Header for health goals section'],
            ['type' => 'recovery_needs', 'value' => 'recovery_needs_body', 'label' => 'Select all that apply to you', 'description' => 'Body text explaining health concerns'],
            ['type' => 'recovery_needs', 'value' => 'weight_loss_need', 'label' => 'Weight loss', 'description' => 'Goal to address weight loss needs'],
            ['type' => 'recovery_needs', 'value' => 'muscle_gain_need', 'label' => 'Muscle gain', 'description' => 'Goal to address muscle gain needs'],
            ['type' => 'recovery_needs', 'value' => 'digestive_health', 'label' => 'Digestive health', 'description' => 'Goal to address digestive health'],
            ['type' => 'recovery_needs', 'value' => 'energy_improvement', 'label' => 'Energy improvement', 'description' => 'Goal to improve energy levels'],
            ['type' => 'recovery_needs', 'value' => 'blood_sugar', 'label' => 'Blood sugar management', 'description' => 'Goal to manage blood sugar'],
            ['type' => 'recovery_needs', 'value' => 'cholesterol', 'label' => 'Cholesterol management', 'description' => 'Goal to manage cholesterol levels'],
            ['type' => 'recovery_needs', 'value' => 'inflammation', 'label' => 'Inflammation reduction', 'description' => 'Goal to reduce inflammation'],
            ['type' => 'recovery_needs', 'value' => 'detoxification', 'label' => 'Detoxification', 'description' => 'Goal to detoxify the body'],
            ['type' => 'recovery_needs', 'value' => 'immune_support', 'label' => 'Immune support', 'description' => 'Goal to support immune system'],
            ['type' => 'recovery_needs', 'value' => 'sleep_improvement', 'label' => 'Sleep improvement', 'description' => 'Goal to improve sleep quality'],
            ['type' => 'recovery_needs', 'value' => 'stress_management', 'label' => 'Stress management', 'description' => 'Goal to manage stress'],
            ['type' => 'recovery_needs', 'value' => 'hair_skin', 'label' => 'Hair/skin health', 'description' => 'Goal to improve hair and skin health'],
            ['type' => 'recovery_needs', 'value' => 'hormone_balance_need', 'label' => 'Hormone balance', 'description' => 'Goal to balance hormones'],
            ['type' => 'recovery_needs', 'value' => 'organ_recovery', 'label' => 'Organ recovery', 'description' => 'Goal to recover from organ damage'],
            ['type' => 'recovery_needs', 'value' => 'post_surgery', 'label' => 'Post-surgery nutrition', 'description' => 'Nutrition focused on recovery after surgery'],
            ['type' => 'recovery_needs', 'value' => 'none_specifically', 'label' => 'None specifically', 'description' => 'No specific recovery needs'],

            // **Favorite and Disliked Foods**
            ['type' => 'foods', 'value' => 'favorite_foods_prompt', 'label' => 'What are your favorite foods?', 'description' => 'Prompt asking for favorite foods'],
            ['type' => 'foods', 'value' => 'disliked_foods_prompt', 'label' => 'Any foods you dislike?', 'description' => 'Prompt asking for disliked foods'],

            // **Nutrition Knowledge**
            ['type' => 'nutrition_knowledge', 'value' => 'nutrition_knowledge_prompt', 'label' => 'How well do you understand nutrition?', 'description' => 'Prompt asking for nutrition knowledge'],
            ['type' => 'nutrition_knowledge', 'value' => 'nutrition_knowledge_header', 'label' => 'Nutrition Knowledge', 'description' => 'Header for nutrition knowledge section'],
            ['type' => 'nutrition_knowledge', 'value' => 'nutrition_knowledge_body', 'label' => 'Select your level', 'description' => 'Body text explaining nutrition knowledge options'],
            ['type' => 'nutrition_knowledge', 'value' => 'beginner', 'label' => 'Beginner', 'description' => 'Beginner level of nutrition knowledge'],
            ['type' => 'nutrition_knowledge', 'value' => 'basic', 'label' => 'Basic', 'description' => 'Basic level of nutrition knowledge'],
            ['type' => 'nutrition_knowledge', 'value' => 'intermediate', 'label' => 'Intermediate', 'description' => 'Intermediate level of nutrition knowledge'],
            ['type' => 'nutrition_knowledge', 'value' => 'advanced', 'label' => 'Advanced', 'description' => 'Advanced level of nutrition knowledge'],
            ['type' => 'nutrition_knowledge', 'value' => 'expert', 'label' => 'Expert', 'description' => 'Expert level of nutrition knowledge'],

            // **Work Type**
            ['type' => 'work_type', 'value' => 'work_type_prompt', 'label' => 'What’s your work type?', 'description' => 'Prompt asking for work type'],
            ['type' => 'work_type', 'value' => 'work_type_header', 'label' => 'Work Type', 'description' => 'Header for work type section'],
            ['type' => 'work_type', 'value' => 'work_type_body', 'label' => 'Select the best match', 'description' => 'Body text explaining work type options'],
            ['type' => 'work_type', 'value' => 'desk_job', 'label' => 'Desk job', 'description' => 'Desk job work type'],
            ['type' => 'work_type', 'value' => 'moderate_physical', 'label' => 'Moderate physical', 'description' => 'Moderate physical work type'],
            ['type' => 'work_type', 'value' => 'demanding_job', 'label' => 'Physically demanding', 'description' => 'Physically demanding work type'],
            ['type' => 'work_type', 'value' => 'student', 'label' => 'Student', 'description' => 'Student work type'],
            ['type' => 'work_type', 'value' => 'parent', 'label' => 'Stay-at-home parent', 'description' => 'Stay-at-home parent work type'],
            ['type' => 'work_type', 'value' => 'retired', 'label' => 'Retired', 'description' => 'Retired work type'],
            ['type' => 'work_type', 'value' => 'unemployed', 'label' => 'Unemployed/Other', 'description' => 'Unemployed or other work type'],

            // **Cooking Time**
            ['type' => 'cooking_time', 'value' => 'cooking_time_prompt', 'label' => 'How much time do you spend cooking?', 'description' => 'Prompt asking for cooking time'],
            ['type' => 'cooking_time', 'value' => 'cooking_time_header', 'label' => 'Cooking Time', 'description' => 'Header for cooking time section'],
            ['type' => 'cooking_time', 'value' => 'cooking_time_body', 'label' => 'Select your available time', 'description' => 'Body text explaining cooking time options'],
            ['type' => 'cooking_time', 'value' => 'minimal_time', 'label' => 'Minimal (0-15 min)', 'description' => 'Minimal cooking time'],
            ['type' => 'cooking_time', 'value' => 'brief_time', 'label' => 'Brief (15-30 min)', 'description' => 'Brief cooking time'],
            ['type' => 'cooking_time', 'value' => 'moderate_time', 'label' => 'Moderate (30-60 min)', 'description' => 'Moderate cooking time'],
            ['type' => 'cooking_time', 'value' => 'extended_time', 'label' => 'Extended (60+ min)', 'description' => 'Extended cooking time'],
            ['type' => 'cooking_time', 'value' => 'batch_cooking', 'label' => 'Batch cooking (weekends)', 'description' => 'Batch cooking for weekends'],

            // **Grocery Access**
            ['type' => 'grocery_access', 'value' => 'grocery_access_prompt', 'label' => 'How easy is grocery shopping for you?', 'description' => 'Prompt asking for grocery access'],
            ['type' => 'grocery_access', 'value' => 'grocery_access_header', 'label' => 'Grocery Access', 'description' => 'Header for grocery access section'],
            ['type' => 'grocery_access', 'value' => 'grocery_access_body', 'label' => 'Select your situation', 'description' => 'Body text explaining grocery access options'],
            ['type' => 'grocery_access', 'value' => 'excellent_variety', 'label' => 'Great variety nearby', 'description' => 'Excellent variety of groceries nearby'],
            ['type' => 'grocery_access', 'value' => 'good_access', 'label' => 'Good basic options', 'description' => 'Good basic grocery options'],
            ['type' => 'grocery_access', 'value' => 'limited_options', 'label' => 'Limited choices', 'description' => 'Limited grocery options available'],
            ['type' => 'grocery_access', 'value' => 'delivery_services', 'label' => 'Use delivery services', 'description' => 'Use of grocery delivery services'],
            ['type' => 'grocery_access', 'value' => 'challenging_access', 'label' => 'Hard to get groceries', 'description' => 'Difficulty in accessing groceries'],

            // **Budget Constraints**
            ['type' => 'budget_constraints', 'value' => 'budget_constraints_prompt', 'label' => 'Do you have a meal budget?', 'description' => 'Prompt asking for meal budget'],
            ['type' => 'budget_constraints', 'value' => 'budget_constraints_header', 'label' => 'Meal Budget', 'description' => 'Header for meal budget section'],
            ['type' => 'budget_constraints', 'value' => 'budget_constraints_body', 'label' => 'Select your situation', 'description' => 'Body text explaining budget options'],
            ['type' => 'budget_constraints', 'value' => 'very_budget', 'label' => 'Strict budget', 'description' => 'Strict budget for meals'],
            ['type' => 'budget_constraints', 'value' => 'moderately_budget', 'label' => 'Moderate budget', 'description' => 'Moderate meal budget'],
            ['type' => 'budget_constraints', 'value' => 'flexible_budget', 'label' => 'Flexible budget', 'description' => 'Flexible meal budget'],
            ['type' => 'budget_constraints', 'value' => 'no_constraints', 'label' => 'No budget concerns', 'description' => 'No constraints on meal budget'],

            // **Exercise Timing**
            ['type' => 'exercise_timing', 'value' => 'exercise_timing_prompt', 'label' => 'When do you usually exercise?', 'description' => 'Prompt asking for exercise timing'],
            ['type' => 'exercise_timing', 'value' => 'exercise_timing_header', 'label' => 'Exercise Timing', 'description' => 'Header for exercise timing section'],
            ['type' => 'exercise_timing', 'value' => 'exercise_timing_body', 'label' => 'Select your usual time', 'description' => 'Body text explaining exercise timing options'],
            ['type' => 'exercise_timing', 'value' => 'early_morning', 'label' => 'Early morning (5-8 AM)', 'description' => 'Exercise time early in the morning'],
            ['type' => 'exercise_timing', 'value' => 'morning', 'label' => 'Morning (8-11 AM)', 'description' => 'Exercise time in the morning'],
            ['type' => 'exercise_timing', 'value' => 'midday', 'label' => 'Midday (11 AM-2 PM)', 'description' => 'Exercise time during midday'],
            ['type' => 'exercise_timing', 'value' => 'afternoon', 'label' => 'Afternoon (2-5 PM)', 'description' => 'Exercise time in the afternoon'],
            ['type' => 'exercise_timing', 'value' => 'evening', 'label' => 'Evening (5-8 PM)', 'description' => 'Exercise time in the evening'],
            ['type' => 'exercise_timing', 'value' => 'night', 'label' => 'Night (8-11 PM)', 'description' => 'Exercise time at night'],
            ['type' => 'exercise_timing', 'value' => 'varies', 'label' => 'Varies/Inconsistent', 'description' => 'Exercise time varies'],

            // **Sleep Hours**
            ['type' => 'sleep_hours', 'value' => 'sleep_hours_prompt', 'label' => 'How many hours do you sleep per night?', 'description' => 'Prompt asking for sleep hours'],
            ['type' => 'sleep_hours', 'value' => 'sleep_hours_header', 'label' => 'Sleep Duration', 'description' => 'Header for sleep duration section'],
            ['type' => 'sleep_hours', 'value' => 'sleep_hours_body', 'label' => 'Select your average', 'description' => 'Body text explaining sleep duration options'],
            ['type' => 'sleep_hours', 'value' => 'less_than_5', 'label' => '< 5 hours', 'description' => 'Sleep duration less than 5 hours'],
            ['type' => 'sleep_hours', 'value' => '5_to_6', 'label' => '5-6 hours', 'description' => 'Sleep duration between 5 to 6 hours'],
            ['type' => 'sleep_hours', 'value' => '6_to_7', 'label' => '6-7 hours', 'description' => 'Sleep duration between 6 to 7 hours'],
            ['type' => 'sleep_hours', 'value' => '7_to_8', 'label' => '7-8 hours', 'description' => 'Sleep duration between 7 to 8 hours'],
            ['type' => 'sleep_hours', 'value' => '8_to_9', 'label' => '8-9 hours', 'description' => 'Sleep duration between 8 to 9 hours'],
            ['type' => 'sleep_hours', 'value' => 'more_than_9', 'label' => '> 9 hours', 'description' => 'Sleep duration more than 9 hours'],
            ['type' => 'sleep_hours', 'value' => 'variable_sleep', 'label' => 'Highly variable', 'description' => 'Variable sleep duration'],

            // **Commitment Level**
            ['type' => 'commitment_level', 'value' => 'commitment_level_prompt', 'label' => 'How committed are you to a structured plan?', 'description' => 'Prompt asking for commitment level'],
            ['type' => 'commitment_level', 'value' => 'commitment_level_header', 'label' => 'Commitment Level', 'description' => 'Header for commitment level section'],
            ['type' => 'commitment_level', 'value' => 'commitment_level_body', 'label' => 'Be honest about your approach', 'description' => 'Body text explaining commitment level'],
            ['type' => 'commitment_level', 'value' => 'very_committed', 'label' => 'Very committed (strict)', 'description' => 'Very committed to the plan'],
            ['type' => 'commitment_level', 'value' => 'mostly', 'label' => 'Mostly committed (90/10)', 'description' => 'Mostly committed to the plan'],
            ['type' => 'commitment_level', 'value' => 'moderate_commitment', 'label' => 'Moderate (80/20)', 'description' => 'Moderately committed to the plan'],
            ['type' => 'commitment_level', 'value' => 'flexible_commitment', 'label' => 'Flexible approach', 'description' => 'Flexible commitment to the plan'],
            ['type' => 'commitment_level', 'value' => 'gradual', 'label' => 'Gradual implementation', 'description' => 'Gradual commitment to the plan'],

            // **Motivation**
            ['type' => 'motivation', 'value' => 'motivation_prompt', 'label' => 'What’s your main reason for dietary changes?', 'description' => 'Prompt asking for motivation'],
            ['type' => 'motivation', 'value' => 'motivation_header', 'label' => 'Motivation', 'description' => 'Header for motivation section'],
            ['type' => 'motivation', 'value' => 'motivation_body', 'label' => 'Select your key reason', 'description' => 'Body text explaining motivation options'],
            ['type' => 'motivation', 'value' => 'better_health', 'label' => 'Better health/longevity', 'description' => 'Motivation for better health'],
            ['type' => 'motivation', 'value' => 'appearance', 'label' => 'Appearance/body goals', 'description' => 'Motivation for appearance or body goals'],
            ['type' => 'motivation', 'value' => 'performance', 'label' => 'Performance boost', 'description' => 'Motivation for performance boost'],
            ['type' => 'motivation', 'value' => 'medical', 'label' => 'Medical necessity', 'description' => 'Motivation for medical necessity'],
            ['type' => 'motivation', 'value' => 'family', 'label' => 'Family/social support', 'description' => 'Motivation for family or social support'],
            ['type' => 'motivation', 'value' => 'event', 'label' => 'Upcoming event/goal', 'description' => 'Motivation for an upcoming event or goal'],
            // **Past Attemps **
            ['type' => 'past_attempts', 'value' => 'past_attempts_prompt', 'label' => 'Have you tried diet plans before?', 'description' => 'Prompt asking about past diet attempts'],
            ['type' => 'past_attempts', 'value' => 'past_attempts_header', 'label' => 'Past Attempts', 'description' => 'Header for past attempts section'],
            ['type' => 'past_attempts', 'value' => 'past_attempts_body', 'label' => 'Select your experience', 'description' => 'Body text explaining past attempts options'],
            ['type' => 'past_attempts', 'value' => 'many_little', 'label' => 'Many tries, little success', 'description' => 'Experience with many tries but little success'],
            ['type' => 'past_attempts', 'value' => 'some_mixed', 'label' => 'Some attempts, mixed results', 'description' => 'Experience with some attempts and mixed results'],
            ['type' => 'past_attempts', 'value' => 'few_limited', 'label' => 'Few tries, limited success', 'description' => 'Experience with few tries and limited success'],
            ['type' => 'past_attempts', 'value' => 'success_regained', 'label' => 'Success before, but regained', 'description' => 'Experience with success, but weight regained'],
            ['type' => 'past_attempts', 'value' => 'first_attempt', 'label' => 'First serious try', 'description' => 'First attempt at a serious diet plan'],

            // **Detail Level**
            ['type' => 'detail_level', 'value' => 'detail_level_prompt', 'label' => 'How detailed should your meal plan be?', 'description' => 'Prompt asking for detail level of meal plan'],
            ['type' => 'detail_level', 'value' => 'detail_level_header', 'label' => 'Detail Level', 'description' => 'Header for detail level section'],
            ['type' => 'detail_level', 'value' => 'detail_level_body', 'label' => 'Select your preference', 'description' => 'Body text explaining detail level options'],
            ['type' => 'detail_level', 'value' => 'very_detailed', 'label' => 'Very detailed (exact amounts)', 'description' => 'Very detailed meal plan with exact amounts'],
            ['type' => 'detail_level', 'value' => 'moderately_detailed', 'label' => 'Moderately detailed', 'description' => 'Moderately detailed meal plan'],
            ['type' => 'detail_level', 'value' => 'general_guidelines', 'label' => 'General guidelines', 'description' => 'General meal plan guidelines'],
            ['type' => 'detail_level', 'value' => 'simple_flexible', 'label' => 'Simple & flexible', 'description' => 'Simple and flexible meal plan'],

            // **Recipe Complexity**
            ['type' => 'recipe_complexity', 'value' => 'recipe_complexity_prompt', 'label' => 'How complex should your recipes be?', 'description' => 'Prompt asking for recipe complexity'],
            ['type' => 'recipe_complexity', 'value' => 'recipe_complexity_header', 'label' => 'Recipe Complexity', 'description' => 'Header for recipe complexity section'],
            ['type' => 'recipe_complexity', 'value' => 'recipe_complexity_body', 'label' => 'Select your preference', 'description' => 'Body text explaining recipe complexity options'],
            ['type' => 'recipe_complexity', 'value' => 'very_simple', 'label' => 'Very simple (few ingredients)', 'description' => 'Very simple recipes with few ingredients'],
            ['type' => 'recipe_complexity', 'value' => 'moderately_simple', 'label' => 'Moderately simple', 'description' => 'Moderately simple recipes'],
            ['type' => 'recipe_complexity', 'value' => 'balanced_complexity', 'label' => 'Balanced complexity', 'description' => 'Balanced complexity in recipes'],
            ['type' => 'recipe_complexity', 'value' => 'complex', 'label' => 'Complex (gourmet)', 'description' => 'Complex gourmet recipes'],

            // **Meal Variety**
            ['type' => 'meal_variety', 'value' => 'meal_variety_prompt', 'label' => 'How much variety do you want in meals?', 'description' => 'Prompt asking for meal variety'],
            ['type' => 'meal_variety', 'value' => 'meal_variety_header', 'label' => 'Meal Variety', 'description' => 'Header for meal variety section'],
            ['type' => 'meal_variety', 'value' => 'meal_variety_body', 'label' => 'Select your preference', 'description' => 'Body text explaining meal variety options'],
            ['type' => 'meal_variety', 'value' => 'moderate_variety', 'label' => 'Moderate variety', 'description' => 'Moderate variety in meals'],
            ['type' => 'meal_variety', 'value' => 'limited_variety', 'label' => 'Limited variety (simple)', 'description' => 'Limited variety with simple meals'],
            ['type' => 'meal_variety', 'value' => 'same_meals', 'label' => 'Same meals repeated', 'description' => 'Same meals repeated every day'],

            // **Additional Requests**
            ['type' => 'additional_requests', 'value' => 'additional_requests_prompt', 'label' => 'Any additional requests or info to share?', 'description' => 'Prompt asking for additional requests or information'],

            // **Organ Recovery**
            ['type' => 'organ_recovery', 'value' => 'organ_recovery_prompt', 'label' => 'Which organs are you focusing on for recovery?', 'description' => 'Prompt asking about organ recovery'],
            ['type' => 'organ_recovery', 'value' => 'organ_recovery_header', 'label' => 'Organ Recovery', 'description' => 'Header for organ recovery section'],
            ['type' => 'organ_recovery', 'value' => 'organ_recovery_body', 'label' => 'Select all that apply', 'description' => 'Body text explaining organ recovery options'],
            ['type' => 'organ_recovery', 'value' => 'liver_rx', 'label' => 'Liver', 'description' => 'Recovery focus on the liver'],
            ['type' => 'organ_recovery', 'value' => 'kidneys_rx', 'label' => 'Kidneys', 'description' => 'Recovery focus on the kidneys'],
            ['type' => 'organ_recovery', 'value' => 'heart_rx', 'label' => 'Heart', 'description' => 'Recovery focus on the heart'],
            ['type' => 'organ_recovery', 'value' => 'lungs', 'label' => 'Lungs', 'description' => 'Recovery focus on the lungs'],
            ['type' => 'organ_recovery', 'value' => 'digestive_system', 'label' => 'Digestive system', 'description' => 'Recovery focus on digestive system'],
            ['type' => 'organ_recovery', 'value' => 'pancreas', 'label' => 'Pancreas', 'description' => 'Recovery focus on the pancreas'],
            ['type' => 'organ_recovery', 'value' => 'other_organ', 'label' => 'Other', 'description' => 'Recovery focus on other organs'],
            ['type' => 'organ_recovery', 'value' => 'organ_recovery_details_prompt', 'label' => 'Please provide more details about the organs you\'re focusing on:', 'description' => 'Prompt for more organ recovery details'],
            ['type' => 'organ_recovery', 'value' => 'surgery_details_prompt', 'label' => 'Please share details about your surgery and when it occurred:', 'description' => 'Prompt for surgery details'],

            // **Religious Diet**
            ['type' => 'religion_diet', 'value' => 'religion_diet_prompt', 'label' => 'Follow a religious diet?', 'description' => 'Prompt asking for religious diet'],
            ['type' => 'religion_diet', 'value' => 'religion_diet_header', 'label' => 'Religious Diet', 'description' => 'Header for religious diet section'],
            ['type' => 'religion_diet', 'value' => 'religion_diet_body', 'label' => 'Select if applicable', 'description' => 'Body text explaining religious diet options'],
            ['type' => 'religion_diet', 'value' => 'kosher', 'label' => 'Kosher (Jewish)', 'description' => 'Kosher diet'],
            ['type' => 'religion_diet', 'value' => 'halal', 'label' => 'Halal (Islamic)', 'description' => 'Halal diet'],
            ['type' => 'religion_diet', 'value' => 'hindu_veg', 'label' => 'Hindu veg', 'description' => 'Hindu vegetarian diet'],
            ['type' => 'religion_diet', 'value' => 'buddhist_veg', 'label' => 'Buddhist veg', 'description' => 'Buddhist vegetarian diet'],
            ['type' => 'religion_diet', 'value' => 'jain_veg', 'label' => 'Jain veg', 'description' => 'Jain vegetarian diet'],
            ['type' => 'religion_diet', 'value' => 'fasting', 'label' => 'Fasting periods', 'description' => 'Fasting periods diet'],
            ['type' => 'religion_diet', 'value' => 'other_religious', 'label' => 'Other diet', 'description' => 'Other religious diet'],
            ['type' => 'religion_diet', 'value' => 'none_religious', 'label' => 'None', 'description' => 'No religious diet'],
            ['type' => 'religion_diet', 'value' => 'religion_diet_details_prompt', 'label' => 'Describe your diet rules', 'description' => 'Prompt for describing diet rules'],
            ['type' => 'religion_diet', 'value' => 'fasting_details_prompt', 'label' => 'Describe fasting (timing, food)', 'description' => 'Prompt for describing fasting details'],

            // **Plan**
            ['type' => 'plan', 'value' => 'plan_prompt', 'label' => 'Choose your plan type:', 'description' => 'Prompt asking for diet plan type'],
            ['type' => 'plan', 'value' => 'complete_plan', 'label' => 'Complete Plan', 'description' => 'Complete diet plan option'],
            ['type' => 'plan', 'value' => 'basic_plan', 'label' => 'Basic Plan', 'description' => 'Basic diet plan option'],
            ['type' => 'plan', 'value' => 'focus_plan', 'label' => 'Food Focus', 'description' => 'Food-focused diet plan option'],
            ['type' => 'plan', 'value' => 'complete_prompt', 'label' => 'Thanks! Generating your diet plan...', 'description' => 'Completion message for generating diet plan'],

            // **Exercise**
            ['type' => 'exercise', 'value' => 'exercise_prompt', 'label' => 'Your exercise pattern?', 'description' => 'Prompt asking for exercise pattern'],
            ['type' => 'exercise', 'value' => 'exercise_header', 'label' => 'Exercise Pattern', 'description' => 'Header for exercise pattern section'],
            ['type' => 'exercise', 'value' => 'exercise_body', 'label' => 'Select your approach', 'description' => 'Body text explaining exercise options'],
            ['type' => 'exercise', 'value' => 'strength', 'label' => 'Strength training', 'description' => 'Strength training exercise'],
            ['type' => 'exercise', 'value' => 'cardio', 'label' => 'Cardio focused', 'description' => 'Cardio focused exercise'],
            ['type' => 'exercise', 'value' => 'mix_exercise', 'label' => 'Mixed approach', 'description' => 'Mixed exercise approach'],
            ['type' => 'exercise', 'value' => 'yoga', 'label' => 'Yoga/low-impact', 'description' => 'Yoga or low-impact exercise'],
            ['type' => 'exercise', 'value' => 'sport', 'label' => 'Sport-specific', 'description' => 'Sport-specific exercise'],
            ['type' => 'exercise', 'value' => 'minimal_ex', 'label' => 'Minimal exercise', 'description' => 'Minimal exercise routine'],

            // **Exercise Frequency**
            ['type' => 'exercise_frequency', 'value' => 'exercise_frequency_prompt', 'label' => 'How often do you exercise?', 'description' => 'Prompt asking for exercise frequency'],
            ['type' => 'exercise_frequency', 'value' => 'exercise_frequency_header', 'label' => 'Exercise Frequency', 'description' => 'Header for exercise frequency section'],
            ['type' => 'exercise_frequency', 'value' => 'exercise_frequency_body', 'label' => 'Select your typical schedule', 'description' => 'Body text explaining exercise frequency options'],
            ['type' => 'exercise_frequency', 'value' => 'daily', 'label' => 'Daily', 'description' => 'Exercise daily'],
            ['type' => 'exercise_frequency', 'value' => '4to6_weekly', 'label' => '4-6 times per week', 'description' => 'Exercise 4-6 times a week'],
            ['type' => 'exercise_frequency', 'value' => '2to3_weekly', 'label' => '2-3 times per week', 'description' => 'Exercise 2-3 times a week'],
            ['type' => 'exercise_frequency', 'value' => 'once_weekly', 'label' => 'Once per week', 'description' => 'Exercise once a week'],
            ['type' => 'exercise_frequency', 'value' => 'rarely', 'label' => 'Rarely/never', 'description' => 'Exercise rarely or never'],

            // **Timeline**
            ['type' => 'timeline', 'value' => 'timeline_prompt', 'label' => 'Your timeline for results?', 'description' => 'Prompt asking for the timeline for results'],
            ['type' => 'timeline', 'value' => 'timeline_header', 'label' => 'Timeline', 'description' => 'Header for timeline section'],
            ['type' => 'timeline', 'value' => 'timeline_body', 'label' => 'Select your timeframe', 'description' => 'Body text explaining timeline options'],
            ['type' => 'timeline', 'value' => 'short_term', 'label' => 'Short term (1-4 wk)', 'description' => 'Short term timeline for results'],
            ['type' => 'timeline', 'value' => 'medium_term', 'label' => 'Medium (1-3 mo)', 'description' => 'Medium term timeline for results'],
            ['type' => 'timeline', 'value' => 'long_term', 'label' => 'Long term (3+ mo)', 'description' => 'Long term timeline for results'],
            ['type' => 'timeline', 'value' => 'lifestyle', 'label' => 'Lifestyle (ongoing)', 'description' => 'Ongoing lifestyle changes'],

            // **Medications**
            ['type' => 'medications', 'value' => 'meds_prompt', 'label' => 'Are you taking any medications?', 'description' => 'Prompt asking about medications'],
            ['type' => 'medications', 'value' => 'meds_header', 'label' => 'Medications', 'description' => 'Header for medications section'],
            ['type' => 'medications', 'value' => 'meds_body', 'label' => 'Select all that apply', 'description' => 'Body text explaining medication options'],
            ['type' => 'medications', 'value' => 'rx_meds', 'label' => 'Prescription medications', 'description' => 'Prescription medications'],
            ['type' => 'medications', 'value' => 'otc_meds', 'label' => 'Over-the-counter medications', 'description' => 'Over-the-counter medications'],
            ['type' => 'medications', 'value' => 'supplements', 'label' => 'Supplements/vitamins', 'description' => 'Supplements or vitamins'],
            ['type' => 'medications', 'value' => 'combo_meds', 'label' => 'Combination therapy', 'description' => 'Combination of therapies'],
            ['type' => 'medications', 'value' => 'no_meds', 'label' => 'None', 'description' => 'No medications'],
            ['type' => 'medications', 'value' => 'meds_detail_prompt', 'label' => 'Please provide details about your medications:', 'description' => 'Prompt for medication details'],

            // **Cuisine Preferences**
            ['type' => 'cuisine_preferences', 'value' => 'cuisine_preferences_prompt', 'label' => 'Select up to 3 cuisines', 'description' => 'Prompt asking for cuisine preferences'],
            ['type' => 'cuisine_preferences', 'value' => 'cuisine_preferences_header', 'label' => 'Cuisine Preferences', 'description' => 'Header for cuisine preferences section'],
            ['type' => 'cuisine_preferences', 'value' => 'cuisine_preferences_body', 'label' => 'Pick your top 3 cuisines', 'description' => 'Body text explaining cuisine selection'],
            ['type' => 'cuisine_preferences', 'value' => 'north_indian', 'label' => 'North Indian', 'description' => 'North Indian cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'south_indian', 'label' => 'South Indian', 'description' => 'South Indian cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'east_indian', 'label' => 'East Indian', 'description' => 'East Indian cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'west_indian', 'label' => 'West Indian', 'description' => 'West Indian cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'punjabi', 'label' => 'Punjabi', 'description' => 'Punjabi cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'gujarati', 'label' => 'Gujarati', 'description' => 'Gujarati cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'bengali', 'label' => 'Bengali', 'description' => 'Bengali cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'mediterranean_cuisine', 'label' => 'Mediterranean', 'description' => 'Mediterranean cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'chinese_cuisine', 'label' => 'Chinese', 'description' => 'Chinese cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'japanese', 'label' => 'Japanese', 'description' => 'Japanese cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'korean', 'label' => 'Korean', 'description' => 'Korean cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'thai', 'label' => 'Thai', 'description' => 'Thai cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'vietnamese', 'label' => 'Vietnamese', 'description' => 'Vietnamese cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'middle_eastern', 'label' => 'Middle Eastern', 'description' => 'Middle Eastern cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'mexican', 'label' => 'Mexican', 'description' => 'Mexican cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'italian_cuisine', 'label' => 'Italian', 'description' => 'Italian cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'continental', 'label' => 'Continental', 'description' => 'Continental cuisine'],
            ['type' => 'cuisine_preferences', 'value' => 'no_specific_cuisine', 'label' => 'No preference', 'description' => 'No specific cuisine preference'],

            // **Meal Timing**
            ['type' => 'meal_timing', 'value' => 'meal_timing_prompt', 'label' => 'Select your meal schedule', 'description' => 'Prompt asking for meal schedule'],
            ['type' => 'meal_timing', 'value' => 'meal_timing_header', 'label' => 'Meal Timing', 'description' => 'Header for meal timing section'],
            ['type' => 'meal_timing', 'value' => 'meal_timing_body', 'label' => 'Choose your preferred pattern', 'description' => 'Body text explaining meal timing options'],
            ['type' => 'meal_timing', 'value' => 'traditional_meals', 'label' => 'Traditional (3 meals)', 'description' => 'Traditional 3 meals per day'],
            ['type' => 'meal_timing', 'value' => 'small_frequent', 'label' => 'Small meals (5-6)', 'description' => 'Small frequent meals (5-6 meals)'],
            ['type' => 'meal_timing', 'value' => 'intermittent_16_8', 'label' => 'Intermittent 16:8', 'description' => 'Intermittent fasting 16:8'],
            ['type' => 'meal_timing', 'value' => 'intermittent_18_6', 'label' => 'Intermittent 18:6', 'description' => 'Intermittent fasting 18:6'],
            ['type' => 'meal_timing', 'value' => 'omad', 'label' => 'OMAD (1 meal/day)', 'description' => 'OMAD (One meal a day)'],
            ['type' => 'meal_timing', 'value' => 'flexible_pattern', 'label' => 'Flexible/No set pattern', 'description' => 'Flexible meal timing or no set pattern'],

            // **Meal Preferences**
            ['type' => 'meal_preferences', 'value' => 'meal_preferences_prompt', 'label' => 'Select your meal preferences', 'description' => 'Prompt asking for meal preferences'],
            ['type' => 'meal_preferences', 'value' => 'meal_preferences_header', 'label' => 'Meal Preferences', 'description' => 'Header for meal preferences section'],
            ['type' => 'meal_preferences', 'value' => 'meal_preferences_body', 'label' => 'Choose all that apply', 'description' => 'Body text explaining meal preferences options'],
            ['type' => 'meal_preferences', 'value' => 'high_protein', 'label' => 'High protein', 'description' => 'High protein meal preference'],
            ['type' => 'meal_preferences', 'value' => 'low_carb', 'label' => 'Low carb', 'description' => 'Low carb meal preference'],
            ['type' => 'meal_preferences', 'value' => 'low_fat', 'label' => 'Low fat', 'description' => 'Low fat meal preference'],
            ['type' => 'meal_preferences', 'value' => 'gluten_free', 'label' => 'Gluten-free', 'description' => 'Gluten-free meal preference'],
            ['type' => 'meal_preferences', 'value' => 'dairy_free', 'label' => 'Dairy-free', 'description' => 'Dairy-free meal preference'],
            ['type' => 'meal_preferences', 'value' => 'sugar_free', 'label' => 'Sugar-free', 'description' => 'Sugar-free meal preference'],
            ['type' => 'meal_preferences', 'value' => 'low_sodium', 'label' => 'Low sodium', 'description' => 'Low sodium meal preference'],
            ['type' => 'meal_preferences', 'value' => 'whole_foods', 'label' => 'Whole foods focus', 'description' => 'Whole foods preference'],
            ['type' => 'meal_preferences', 'value' => 'plant_based', 'label' => 'Plant-based', 'description' => 'Plant-based meal preference'],
            ['type' => 'meal_preferences', 'value' => 'seasonal', 'label' => 'Local/Seasonal', 'description' => 'Local and seasonal ingredients'],
            ['type' => 'meal_preferences', 'value' => 'balanced_macros', 'label' => 'Balanced macros', 'description' => 'Balanced macronutrients preference'],
            ['type' => 'meal_preferences', 'value' => 'home_cooking', 'label' => 'Home-cooked meals', 'description' => 'Home-cooked meals preference'],
            ['type' => 'meal_preferences', 'value' => 'no_specific_prefs', 'label' => 'No specific preference', 'description' => 'No specific meal preference'],

            // **Daily Schedule**
            ['type' => 'daily_schedule', 'value' => 'schedule_prompt', 'label' => 'Your typical daily schedule?', 'description' => 'Prompt asking for daily schedule'],
            ['type' => 'daily_schedule', 'value' => 'schedule_header', 'label' => 'Daily Schedule', 'description' => 'Header for daily schedule section'],
            ['type' => 'daily_schedule', 'value' => 'schedule_body', 'label' => 'Select your typical routine', 'description' => 'Body text explaining daily schedule options'],
            ['type' => 'daily_schedule', 'value' => 'early_riser', 'label' => 'Early riser', 'description' => 'Early riser daily schedule'],
            ['type' => 'daily_schedule', 'value' => 'standard', 'label' => 'Standard hours', 'description' => 'Standard daily hours'],
            ['type' => 'daily_schedule', 'value' => 'late_riser', 'label' => 'Late riser', 'description' => 'Late riser daily schedule'],
            ['type' => 'daily_schedule', 'value' => 'night_shift', 'label' => 'Night shift', 'description' => 'Night shift daily schedule'],
            ['type' => 'daily_schedule', 'value' => 'irregular', 'label' => 'Irregular hours', 'description' => 'Irregular daily schedule'],

            // **Cooking Capability**
            ['type' => 'cooking_capability', 'value' => 'cooking_prompt', 'label' => 'Your cooking capability?', 'description' => 'Prompt asking about cooking capability'],
            ['type' => 'cooking_capability', 'value' => 'cooking_header', 'label' => 'Cooking Capability', 'description' => 'Header for cooking capability section'],
            ['type' => 'cooking_capability', 'value' => 'cooking_body', 'label' => 'Select your cooking situation', 'description' => 'Body text explaining cooking capability options'],
            ['type' => 'cooking_capability', 'value' => 'full_cooking', 'label' => 'Full cooking facilities', 'description' => 'Full cooking facilities available'],
            ['type' => 'cooking_capability', 'value' => 'basic_cooking', 'label' => 'Basic cooking facilities', 'description' => 'Basic cooking facilities available'],
            ['type' => 'cooking_capability', 'value' => 'minimal_cooking', 'label' => 'Minimal cooking facilities', 'description' => 'Minimal cooking facilities available'],
            ['type' => 'cooking_capability', 'value' => 'prepared_food', 'label' => 'Mostly prepared foods', 'description' => 'Mostly rely on prepared foods'],
            ['type' => 'cooking_capability', 'value' => 'cooking_help', 'label' => 'Have cooking assistance', 'description' => 'Need assistance for cooking'],

            // **Stress and Sleep**
            ['type' => 'stress_and_sleep', 'value' => 'stress_prompt', 'label' => 'Stress and sleep patterns?', 'description' => 'Prompt asking about stress and sleep patterns'],
            ['type' => 'stress_and_sleep', 'value' => 'stress_header', 'label' => 'Stress & Sleep', 'description' => 'Header for stress and sleep section'],
            ['type' => 'stress_and_sleep', 'value' => 'stress_body', 'label' => 'Select your situation', 'description' => 'Body text explaining stress and sleep options'],
            ['type' => 'stress_and_sleep', 'value' => 'low_good', 'label' => 'Low stress, good sleep', 'description' => 'Low stress, good sleep pattern'],
            ['type' => 'stress_and_sleep', 'value' => 'moderate_ok', 'label' => 'Moderate stress, OK sleep', 'description' => 'Moderate stress with acceptable sleep'],
            ['type' => 'stress_and_sleep', 'value' => 'high_enough', 'label' => 'High stress, enough sleep', 'description' => 'High stress but sufficient sleep'],
            ['type' => 'stress_and_sleep', 'value' => 'low_poor', 'label' => 'Low stress, poor sleep', 'description' => 'Low stress but poor sleep'],
            ['type' => 'stress_and_sleep', 'value' => 'high_poor', 'label' => 'High stress, poor sleep', 'description' => 'High stress with poor sleep'],
 
            // **Additional Requests**
            ['type' => 'additional_requests', 'value' => 'additional_prompt', 'label' => 'Any additional requests or specifics?', 'description' => 'Prompt for additional requests or specifics'],

            // **Meal Variety**
            ['type' => 'meal_variety', 'value' => 'variety_prompt', 'label' => 'Desired meal variety?', 'description' => 'Prompt asking for desired meal variety'],
            ['type' => 'meal_variety', 'value' => 'variety_header', 'label' => 'Meal Variety', 'description' => 'Header for meal variety section'],
            ['type' => 'meal_variety', 'value' => 'variety_body', 'label' => 'Select your preference', 'description' => 'Body text explaining meal variety options'],
            ['type' => 'meal_variety', 'value' => 'high_variety', 'label' => 'High variety (different meals daily)', 'description' => 'High variety meals with different daily options'],
            ['type' => 'meal_variety', 'value' => 'moderate_var', 'label' => 'Moderate variety (some repetition)', 'description' => 'Moderate variety meals with some repetition'],
            ['type' => 'meal_variety', 'value' => 'limited_var', 'label' => 'Limited variety (weekly rotation)', 'description' => 'Limited variety with weekly meal rotation'],
            ['type' => 'meal_variety', 'value' => 'repetitive', 'label' => 'Repetitive (same daily pattern)', 'description' => 'Repetitive meals with the same daily pattern'],

            // **Body Type**
            ['type' => 'body_type', 'value' => 'body_type_prompt', 'label' => 'Which best describes your body type?', 'description' => 'Prompt asking for body type'],
            ['type' => 'body_type', 'value' => 'body_type_header', 'label' => 'Body Type', 'description' => 'Header for body type section'],
            ['type' => 'body_type', 'value' => 'body_type_body', 'label' => 'Select your natural physique', 'description' => 'Body text explaining body type options'],
            ['type' => 'body_type', 'value' => 'ectomorph', 'label' => 'Naturally thin', 'description' => 'Ectomorph body type'],
            ['type' => 'body_type', 'value' => 'mesomorph', 'label' => 'Athletic build', 'description' => 'Mesomorph body type'],
            ['type' => 'body_type', 'value' => 'endomorph', 'label' => 'Naturally stocky', 'description' => 'Endomorph body type'],
            ['type' => 'body_type', 'value' => 'combination', 'label' => 'Combination', 'description' => 'Combination body type'],
            ['type' => 'body_type', 'value' => 'not_sure', 'label' => 'Not sure', 'description' => 'Uncertain about body type'],

            // **Medical History**
            ['type' => 'medical_history', 'value' => 'medical_history_prompt', 'label' => 'Any past medical conditions?', 'description' => 'Prompt asking for past medical conditions'],
            ['type' => 'medical_history', 'value' => 'medical_history_header', 'label' => 'Medical History', 'description' => 'Header for medical history section'],
            ['type' => 'medical_history', 'value' => 'medical_history_body', 'label' => 'Select all that apply', 'description' => 'Body text explaining medical history options'],
            ['type' => 'medical_history', 'value' => 'heart_disease', 'label' => 'Heart disease', 'description' => 'Heart disease condition'],
            ['type' => 'medical_history', 'value' => 'high_cholesterol', 'label' => 'High cholesterol', 'description' => 'High cholesterol condition'],
            ['type' => 'medical_history', 'value' => 'cancer', 'label' => 'Cancer', 'description' => 'Cancer condition'],
            ['type' => 'medical_history', 'value' => 'autoimmune', 'label' => 'Autoimmune issue', 'description' => 'Autoimmune issues'],
            ['type' => 'medical_history', 'value' => 'gastrointestinal', 'label' => 'Gastrointestinal', 'description' => 'Gastrointestinal issues'],
            ['type' => 'medical_history', 'value' => 'mental_health', 'label' => 'Mental health issue', 'description' => 'Mental health issues'],
            ['type' => 'medical_history', 'value' => 'none_medical', 'label' => 'None of these', 'description' => 'No medical conditions'],

            // **Water Intake**
            ['type' => 'water_intake', 'value' => 'water_intake_prompt', 'label' => 'Daily water intake?', 'description' => 'Prompt asking for daily water intake'],
            ['type' => 'water_intake', 'value' => 'water_intake_header', 'label' => 'Water Intake', 'description' => 'Header for water intake section'],
            ['type' => 'water_intake', 'value' => 'water_intake_body', 'label' => 'Select your typical consumption', 'description' => 'Body text explaining water intake options'],
            ['type' => 'water_intake', 'value' => 'water_lt1', 'label' => 'Less than 1 liter', 'description' => 'Less than 1 liter of water daily'],
            ['type' => 'water_intake', 'value' => 'water_1to2', 'label' => '1-2 liters', 'description' => '1-2 liters of water daily'],
            ['type' => 'water_intake', 'value' => 'water_2to3', 'label' => '2-3 liters', 'description' => '2-3 liters of water daily'],
            ['type' => 'water_intake', 'value' => 'water_gt3', 'label' => 'More than 3 liters', 'description' => 'More than 3 liters of water daily'],
            ['type' => 'water_intake', 'value' => 'water_unknown', 'label' => 'Don\'t track water intake', 'description' => 'Do not track daily water intake'],

            // **Weight Goal**
            ['type' => 'weight_goal', 'value' => 'weight_goal_prompt', 'label' => 'Your desired rate of weight change?', 'description' => 'Prompt asking for weight goal'],
            ['type' => 'weight_goal', 'value' => 'weight_goal_header', 'label' => 'Weight Goal', 'description' => 'Header for weight goal section'],
            ['type' => 'weight_goal', 'value' => 'weight_goal_body', 'label' => 'Select your preferred pace', 'description' => 'Body text explaining weight goal options'],
            ['type' => 'weight_goal', 'value' => 'rapid_loss', 'label' => 'Rapid weight loss', 'description' => 'Rapid weight loss goal'],
            ['type' => 'weight_goal', 'value' => 'moderate_loss', 'label' => 'Moderate weight loss', 'description' => 'Moderate weight loss goal'],
            ['type' => 'weight_goal', 'value' => 'slow_loss', 'label' => 'Slow, steady weight loss', 'description' => 'Slow and steady weight loss goal'],
            ['type' => 'weight_goal', 'value' => 'slight_gain', 'label' => 'Slight weight gain', 'description' => 'Slight weight gain goal'],
            ['type' => 'weight_goal', 'value' => 'moderate_gain', 'label' => 'Moderate weight gain', 'description' => 'Moderate weight gain goal'],
            ['type' => 'weight_goal', 'value' => 'significant_gain', 'label' => 'Significant weight gain', 'description' => 'Significant weight gain goal'],

        ];

        DB::table('attributes')->insert($attributes);
    }
}